### ISSUE TITLE
Portable atoms

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-labs#27]
We probably want the atomic decorators to do nothing if we're server side with a portable atom.
Maybe. 
I think if a method decorated with say `action` or `selector` was called server side then it might just throw.
It might not (I haven't tried yet).

**Comment by meatballs** [comment]
it does - In my example app, I had both the TodoList atom , the subscriber and the Todo portable class in the same module at one point - the server side didn't like at all when I tried to import the portable class!

**Comment by meatballs** [comment]
I've changed the MWE to use `@portable_atom` but I still get an error:
```
anvil.server.SerializationError: No such serializable type: __main__.Todo at msg['args'][0]

    at /downlink/anvil/_server.py:1014
    called from /downlink/anvil/_serialise.py:71
    called from Module1, line 12
```

**Comment by s-cork** [comment]
Is it the startup form?
I think that just happens

**Comment by meatballs** [comment]
Really?!!! I've never come across that particular wrinkle!

But then, I'm not likely to define a model in a startup module except for an MWE. I'll tinker further...

**Comment by s-cork** [comment]
Yeah - the startup module is always `__main__` in anvil client side
So it gets registered as existing in the `__main__` module
And then the serialization mechanism says - where do I find this class - oh it's in `__main__` Let's go
... fail

**Comment by meatballs** [comment]
Yep. That did the trick. All good! 

Mental note of that one duly taken

**Comment by s-cork** [comment]
I made the mental note yesterday when I did the exact same thing in trying to test it 😉
