### ISSUE TITLE
Render not getting called for portable atom

### ISSUE THREAD

**Issue by meatballs** [anvilistas/anvil-labs#29]
MWE showing a difference in behaviour between atoms and portable atoms:

https://anvil.works/build#clone:RKXFVVP5HZLAZ3OO=FARAXTT2S5F57ST6YWM2J7U2

**Comment by s-cork** [comment]
haha oh god 🤦‍♂️

**Comment by meatballs** [comment]
I really must get to grips with the code for atomic so I can fix these myself. It felt like a daft one!
