### ISSUE TITLE
Subscribe not working on first call for server side portable atom

### ISSUE THREAD

**Issue by meatballs** [anvilistas/anvil-labs#32]
If a portable atom is created server side and sent back to the client, subscribed functions don't work in quite the same manner.

MWE: https://anvil.works/build#clone:R7UC642A2YGE46CI=LJYJS2572B5QSNXGL5TFAWUI

**Comment by s-cork** [comment]
that'll be the deserialize method
We'll need to create one I think
the default one in anvil is `self.__dict__.update(data)`
but that won't trigger any actions for us
