### ISSUE TITLE
`__dict__` key error on a `@portable_atom`

### ISSUE THREAD

**Issue by theref** [anvilistas/anvil-labs#50]
I have a reaction defined which depends on all the attributes of a `portable_atom`.

```
def _react_to(self, particle):
    def depend_on():
        for attr in particle.__dict__:
            getattr(particle, attr)
        return particle
```

However I get this error when the reaction occurs:

```
action: changing: DictAtom['595ac68a-6e5d-4b37-9676-803212af439b'] = <Group atom>
reaction: depend_on
KeyError: __dict__

    at app/anvil_labs/atomic/atoms.py:102
    called from app/anvil_labs/atomic/atoms.py:67
```

I thought all objects had to have `__dict__` defined?

**Comment by meatballs** [comment]
I think this is caused when a portable atom class is a subclass of something else. MWE at:

https://anvil.works/build#clone:F4AHYWIWR67LVRZL=2734RXP5EQXQAYAQOKSNUM3C

Changing L12 in there from:
```class Thing(_AbstractThing)```

to
```class Thing:```

makes the problem disappear

**Comment by s-cork** [comment]
Oh my that is a piece of python internals. 

Not everything has to have a `__dict__`. If you define a class with `__slots__` then it's instance won't get that property. 

What's happening there is that the class won't receive a `__dict__` descriptor.

Try inspecting the `__dict__` of a class that does and doesn't define `__slots__`. You'll see one has a key `__dict__' and one doesnt. 

The same is true of subclasses. The `__dict__` descriptor is inherited. (With some nuance to the inheritance rules). 

Try replacing the `base.__dict__["__dict__"]` with `super().__dict__`. This should walk the `__mro__` and find the base class that has the descriptor.

**Comment by meatballs** [comment]
I've always said inheritance is a code smell. This is just further ammunition!

**Comment by s-cork** [comment]
I dunno I think it's more of a case of super considered super.
