### ISSUE TITLE
Duplication prevention when saving events

### ISSUE THREAD

**Issue by theref** [anvilistas/anvil-labs#54]
I think the duplication prevention could be improved. At the moment there is a flag `prevent_duplication=True` in  `save_events`. If `True` this raises an error whenever a `Change` is made that would have an empty diff. If `False`, it writes a `Change` event to the db where the diff is `None`.

I'm not sure raising an error is quite correct, if I want to save the state of an object, that should just happen regardless of duplication. Could the flag be changed to `record_duplication` if `True`, it writes a `Change` event to the db where the diff is `None`. If `False`, the event (with no actual change) is just ignored.

**Comment by meatballs** [comment]
I agree. If you're asking to save an event which already exists, the choice should be 'do nothing' or 'save it again anyway'. There's no real need to raise an error.
