### ISSUE TITLE
Support require_user and possibly Make `require_user=True` the default for `@callable`?

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-labs#63]
I've recently seen it described as a best practice to require authorization by default, and that seems sensible in my (limited) experience.

So I'd propose having `require_user` default to `True`. It would then be necessary to explicitly set it to `False` if you don't want to require authorization. (Or you could still [set it to a function](https://anvil.works/docs/server#advanced) to restrict permissions further.)

**Comment by meatballs** [comment]
The users service isn't enabled by default on an anvil app and I'd prefer our stuff to work by default on any app.

**Comment by hugetim** [comment]
As long as I can pass a `require_user` argument to the kompot version of `@callable`, it's easy enough to wrap it with my own function to accomplish this effect.

**Comment by s-cork** [comment]
We haven't yet implemented the decorator to support require user. So reopening this
