### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by rhurlbatt** [anvilistas/anvil-labs#90]
@s-cork since the PR was merged we are getting this error in a test app that depends on Anvil Labs. The Defer script had been added (to line 3 of Native Libraries)

`6d6f72e2-8fea-48ef-b4ca-c4b007ae1845:6 Uncaught SyntaxError: Invalid or unexpected token (at 6d6f72e2-8fea-48ef-b4ca-c4b007ae1845:6:1767716)`

**Comment by s-cork** [comment]
I think this is now fixed
